services:
  webtest:
    image: webtest:latest
    build:
      context: .
      dockerfile: tasks/webtest/Dockerfile
  webgen:
    image: webgen:latest
    build:
      context: .
      dockerfile: tasks/webgen/Dockerfile
  ab_testing:
    image: ab_testing:latest
    build:
      context: .
      dockerfile: tasks/ab_testing/Dockerfile
  replicatorbench:
    image: replicatorbench:latest
    build:
      context: .
      dockerfile: tasks/replicatorbench/Dockerfile