task_id: "docbench"
data_path: "data/docbench_hard.json"
# model_name: "qwen3-coder-30b-a3b"
model_name: "ministral-3-8b"
prompt_name: "default"

# GEPA settings
# reflection_lm: "gemini-3.1-pro-preview"
reflection_lm: "gemini-3-flash-preview"
max_cost: 8.0
seed: 3

# Evaluation
eval_lm: "gemini-3-flash-preview"
agent_batch_size: 8
eval_batch_size: 16

# Data
max_examples: 20
train_ratio: 0.5

# Reflection
use_adaptation_guide: false

# Docker
use_docker: true
server_image: "docbench:latest"
max_time: 600
