task_id: "docbench"
data_path: "data/docbench.json"
# model_name: "gemini-3.1-pro-preview"
model_name: "qwen3-coder-30b-a3b"
prompt_name: "default"

max_examples: 10
n_responses: 1
agent_batch_size: 4
resume: true

is_agentic: true
use_docker: false
server_image: ""

eval_lm: "gemini-3-flash-preview"
