task_id: "webtest"
data_path: "data/webtest.csv"
model_name: "qwen3-coder-30b-a3b"
prompt_name: "static"

# GEPA settings
reflection_lm: "gemini-3.1-pro-preview"
max_metric_calls: 10
seed: 4

# Evaluation
eval_lm: "gemini-3-flash-preview"

# Data
max_examples: 5
train_ratio: 0.6

# Reflection
use_adaptation_guide: true

# Docker
use_docker: true
server_image: "webtest:latest"
